# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import employees_pb2 as employees__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in employees_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmployeesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEmployees = channel.unary_unary(
                '/EmployeesService/ListEmployees',
                request_serializer=employees__pb2.ListEmployeesRequest.SerializeToString,
                response_deserializer=employees__pb2.ListEmployeesResponse.FromString,
                _registered_method=True)
        self.GetEmployee = channel.unary_unary(
                '/EmployeesService/GetEmployee',
                request_serializer=employees__pb2.GetEmployeeRequest.SerializeToString,
                response_deserializer=employees__pb2.GetEmployeeResponse.FromString,
                _registered_method=True)
        self.CreateEmployee = channel.unary_unary(
                '/EmployeesService/CreateEmployee',
                request_serializer=employees__pb2.CreateEmployeeRequest.SerializeToString,
                response_deserializer=employees__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.UpdateEmployee = channel.unary_unary(
                '/EmployeesService/UpdateEmployee',
                request_serializer=employees__pb2.UpdateEmployeeRequest.SerializeToString,
                response_deserializer=employees__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.DeleteEmployee = channel.unary_unary(
                '/EmployeesService/DeleteEmployee',
                request_serializer=employees__pb2.DeleteEmployeeRequest.SerializeToString,
                response_deserializer=employees__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/EmployeesService/GetHistory',
                request_serializer=employees__pb2.GetHistoryRequest.SerializeToString,
                response_deserializer=employees__pb2.GetHistoryResponse.FromString,
                _registered_method=True)
        self.ListDepartments = channel.unary_unary(
                '/EmployeesService/ListDepartments',
                request_serializer=employees__pb2.ListDepartmentsRequest.SerializeToString,
                response_deserializer=employees__pb2.ListDepartmentsResponse.FromString,
                _registered_method=True)
        self.GetDepartment = channel.unary_unary(
                '/EmployeesService/GetDepartment',
                request_serializer=employees__pb2.GetDepartmentRequest.SerializeToString,
                response_deserializer=employees__pb2.GetDepartmentResponse.FromString,
                _registered_method=True)
        self.CreateDepartment = channel.unary_unary(
                '/EmployeesService/CreateDepartment',
                request_serializer=employees__pb2.CreateDepartmentRequest.SerializeToString,
                response_deserializer=employees__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.UpdateDepartment = channel.unary_unary(
                '/EmployeesService/UpdateDepartment',
                request_serializer=employees__pb2.UpdateDepartmentRequest.SerializeToString,
                response_deserializer=employees__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.DeleteDepartment = channel.unary_unary(
                '/EmployeesService/DeleteDepartment',
                request_serializer=employees__pb2.DeleteDepartmentRequest.SerializeToString,
                response_deserializer=employees__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.ListPositions = channel.unary_unary(
                '/EmployeesService/ListPositions',
                request_serializer=employees__pb2.ListPositionsRequest.SerializeToString,
                response_deserializer=employees__pb2.ListPositionsResponse.FromString,
                _registered_method=True)
        self.GetPosition = channel.unary_unary(
                '/EmployeesService/GetPosition',
                request_serializer=employees__pb2.GetPositionRequest.SerializeToString,
                response_deserializer=employees__pb2.GetPositionResponse.FromString,
                _registered_method=True)
        self.CreatePosition = channel.unary_unary(
                '/EmployeesService/CreatePosition',
                request_serializer=employees__pb2.CreatePositionRequest.SerializeToString,
                response_deserializer=employees__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.UpdatePosition = channel.unary_unary(
                '/EmployeesService/UpdatePosition',
                request_serializer=employees__pb2.UpdatePositionRequest.SerializeToString,
                response_deserializer=employees__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.DeletePosition = channel.unary_unary(
                '/EmployeesService/DeletePosition',
                request_serializer=employees__pb2.DeletePositionRequest.SerializeToString,
                response_deserializer=employees__pb2.OperationResponse.FromString,
                _registered_method=True)


class EmployeesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListEmployees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDepartments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDepartment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDepartment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDepartment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDepartment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmployeesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListEmployees': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEmployees,
                    request_deserializer=employees__pb2.ListEmployeesRequest.FromString,
                    response_serializer=employees__pb2.ListEmployeesResponse.SerializeToString,
            ),
            'GetEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmployee,
                    request_deserializer=employees__pb2.GetEmployeeRequest.FromString,
                    response_serializer=employees__pb2.GetEmployeeResponse.SerializeToString,
            ),
            'CreateEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEmployee,
                    request_deserializer=employees__pb2.CreateEmployeeRequest.FromString,
                    response_serializer=employees__pb2.OperationResponse.SerializeToString,
            ),
            'UpdateEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEmployee,
                    request_deserializer=employees__pb2.UpdateEmployeeRequest.FromString,
                    response_serializer=employees__pb2.OperationResponse.SerializeToString,
            ),
            'DeleteEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEmployee,
                    request_deserializer=employees__pb2.DeleteEmployeeRequest.FromString,
                    response_serializer=employees__pb2.OperationResponse.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=employees__pb2.GetHistoryRequest.FromString,
                    response_serializer=employees__pb2.GetHistoryResponse.SerializeToString,
            ),
            'ListDepartments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDepartments,
                    request_deserializer=employees__pb2.ListDepartmentsRequest.FromString,
                    response_serializer=employees__pb2.ListDepartmentsResponse.SerializeToString,
            ),
            'GetDepartment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDepartment,
                    request_deserializer=employees__pb2.GetDepartmentRequest.FromString,
                    response_serializer=employees__pb2.GetDepartmentResponse.SerializeToString,
            ),
            'CreateDepartment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDepartment,
                    request_deserializer=employees__pb2.CreateDepartmentRequest.FromString,
                    response_serializer=employees__pb2.OperationResponse.SerializeToString,
            ),
            'UpdateDepartment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDepartment,
                    request_deserializer=employees__pb2.UpdateDepartmentRequest.FromString,
                    response_serializer=employees__pb2.OperationResponse.SerializeToString,
            ),
            'DeleteDepartment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDepartment,
                    request_deserializer=employees__pb2.DeleteDepartmentRequest.FromString,
                    response_serializer=employees__pb2.OperationResponse.SerializeToString,
            ),
            'ListPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPositions,
                    request_deserializer=employees__pb2.ListPositionsRequest.FromString,
                    response_serializer=employees__pb2.ListPositionsResponse.SerializeToString,
            ),
            'GetPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosition,
                    request_deserializer=employees__pb2.GetPositionRequest.FromString,
                    response_serializer=employees__pb2.GetPositionResponse.SerializeToString,
            ),
            'CreatePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePosition,
                    request_deserializer=employees__pb2.CreatePositionRequest.FromString,
                    response_serializer=employees__pb2.OperationResponse.SerializeToString,
            ),
            'UpdatePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePosition,
                    request_deserializer=employees__pb2.UpdatePositionRequest.FromString,
                    response_serializer=employees__pb2.OperationResponse.SerializeToString,
            ),
            'DeletePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePosition,
                    request_deserializer=employees__pb2.DeletePositionRequest.FromString,
                    response_serializer=employees__pb2.OperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EmployeesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('EmployeesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmployeesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListEmployees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/ListEmployees',
            employees__pb2.ListEmployeesRequest.SerializeToString,
            employees__pb2.ListEmployeesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/GetEmployee',
            employees__pb2.GetEmployeeRequest.SerializeToString,
            employees__pb2.GetEmployeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/CreateEmployee',
            employees__pb2.CreateEmployeeRequest.SerializeToString,
            employees__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/UpdateEmployee',
            employees__pb2.UpdateEmployeeRequest.SerializeToString,
            employees__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/DeleteEmployee',
            employees__pb2.DeleteEmployeeRequest.SerializeToString,
            employees__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/GetHistory',
            employees__pb2.GetHistoryRequest.SerializeToString,
            employees__pb2.GetHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDepartments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/ListDepartments',
            employees__pb2.ListDepartmentsRequest.SerializeToString,
            employees__pb2.ListDepartmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDepartment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/GetDepartment',
            employees__pb2.GetDepartmentRequest.SerializeToString,
            employees__pb2.GetDepartmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDepartment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/CreateDepartment',
            employees__pb2.CreateDepartmentRequest.SerializeToString,
            employees__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDepartment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/UpdateDepartment',
            employees__pb2.UpdateDepartmentRequest.SerializeToString,
            employees__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDepartment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/DeleteDepartment',
            employees__pb2.DeleteDepartmentRequest.SerializeToString,
            employees__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/ListPositions',
            employees__pb2.ListPositionsRequest.SerializeToString,
            employees__pb2.ListPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/GetPosition',
            employees__pb2.GetPositionRequest.SerializeToString,
            employees__pb2.GetPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/CreatePosition',
            employees__pb2.CreatePositionRequest.SerializeToString,
            employees__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/UpdatePosition',
            employees__pb2.UpdatePositionRequest.SerializeToString,
            employees__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeesService/DeletePosition',
            employees__pb2.DeletePositionRequest.SerializeToString,
            employees__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
